sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - 5
  - 5.1
  - 4
  - 4.2
  - 4.1
  - 4.0
  - iojs
before_install:
  - npm i -g npm
before_script:
  - npm prune
after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - npm run report-coverage
