sudo: false

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 4
  - 5
  - 6
  - 7
  - 8

before_install:
  - npm install npm -g
  - npm install yarn -g
  - npm cache verify
  - npm prune
  - npm update
  - yarn

before_script:
  - npm prune

script:
  - node --version
  - npm --version
  - yarn --version
  - npm test

after_success:
  - npm run report-coverage
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
