sudo: false

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - CC_TEST_REPORTER_ID=54632afea2654c05326d460d2088caf3a7189015fd1cff3e7d73fc899e6286e8

node_js:
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4

install:
  - travis_retry yarn install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - node --version
  - npm --version
  - yarn --version
  - npm test

after_success:
  - npm run report-coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm install -g travis-deploy-once semantic-release && travis-deploy-once "semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
